version: '2'
services:
    lb:
        image: trydock/ngx-lb
        ports:
            - "80:80"
            - "443:443"
            - "8089:8089"
            - "9000:9000"
        volumes:
            - ./files/etc/nginx/conf.d:/etc/nginx/conf.d
            - ./files/var/www/htdocs:/var/www/htdocs
